name: Weekly Dev CI

on:
  pull_request:
    branches: [ "Weekly/*" ]

jobs:
  test:
    name: Lint and Unit Tests
    runs-on: ubuntu-latest

    # PR 코멘트 및 리뷰 작성을 위한 권한 설정
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Gradle Caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

        # Gradle 스크립트 실행을 위한 권한 설정
      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

        # Convention Check 후 PR 리뷰로 결과 전송
      - name: Run Ktlint and Publish Test Results
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          android: true
          fail_on_error: true
          level: warning

        # 유닛 테스트 후 PR 코멘트로 결과 전송
      - name: Run Unit Test
        if: success() || failure()
        run: ./gradlew test

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: success() || failure()
        with:
          junit_files: '**/build/test-results/*/TEST-*.xml'
